[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
  https://github.com/ESP32Async/ESPAsyncWebServer @ ^3.7.7
  https://github.com/ESP32Async/AsyncTCP @ ^3.3.8
  marvinroger/AsyncMqttClient @ ^0.9.0
  adafruit/DHT sensor library @ ^1.4.6
  bblanchon/ArduinoJson @ ^7.0.4

build_flags =
  -DASYNCWEBSERVER_REGEX
